export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

export const SET_COMPLETE_MESSAGE = 'SET_COMPLETE_MESSAGE';
export const CLEAR_COMPLETE_MESSAGE = 'CLEAR_COMPLETE_MESSAGE';

export const SET_RATINGS = 'SET_RATINGS';

export const SET_ACTIVE_SORT = 'SET_ACTIVE_SORT';
export const SET_IDS = 'SET_IDS';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const CLEAR_ACTIVE_USER = 'CLEAR_ACTIVE_USER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
